#!/bin/bash
# Vault Health Check — audit vault structure, links, frontmatter, keyword map
# Run: bash ~/.claude/hooks/vault-health-check.sh
# Output: 00_INBOX/vault_health_YYYY-MM-DD.md + session summary

VAULT_ROOT="$HOME/vault_obsidian_brajakara"
KEYWORD_MAP="$HOME/.claude/vault-keyword-map.tsv"
REPORT="$VAULT_ROOT/00_INBOX/vault_health_$(date +%Y-%m-%d).md"
REKAM_JEJAK="$VAULT_ROOT/07_PROFIL (Professional Identity)/rekam_jejak.md"

echo ""
echo "🏥 Vault Health Check running..."
echo "   Report: $REPORT"
echo ""

ISSUE_COUNT=0

cat > "$REPORT" << EOF
---
type: inbox
category: vault
tags: [vault-health, audit]
date: $(date +%Y-%m-%d)
---

# Vault Health Report — $(date +%Y-%m-%d)

> Auto-generated by \`vault-health-check.sh\`. Review and resolve issues below.

---

EOF

# ============ CHECK 1: BROKEN WIKILINKS ============
echo "[1/5] Scanning for broken wikilinks..."

echo "## 🔗 Broken Wikilinks" >> "$REPORT"
echo "" >> "$REPORT"

BROKEN_LINKS=0

while IFS= read -r file; do
    # Extract all wikilinks from file
    while IFS= read -r link; do
        # Get just the filename part (before | )
        link_target=$(echo "$link" | sed 's/|.*//' | tr -d '[]')
        
        # Skip date patterns (YYYY-MM-DD)
        if echo "$link_target" | grep -qE "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"; then
            continue
        fi
        
        # Search for the file in vault
        link_file="${link_target##*/}"
        found=0
        
        if find "$VAULT_ROOT" -name "${link_file}.md" -o -name "${link_file}" 2>/dev/null | grep -q .; then
            found=1
        fi
        
        if [ $found -eq 0 ]; then
            rel_file="${file#$VAULT_ROOT/}"
            echo "- \`$rel_file\` → \`[[${link_target}]]\` (target not found)" >> "$REPORT"
            BROKEN_LINKS=$((BROKEN_LINKS + 1))
        fi
    done < <(grep -oP '\[\[([^\]]+)\]\]' "$file" 2>/dev/null | grep -oP '(?<=\[\[)[^\]]+' || true)
done < <(find "$VAULT_ROOT" -name "*.md" -not -path "*/.git/*" -not -path "*/.obsidian/*")

if [ $BROKEN_LINKS -eq 0 ]; then
    echo "✓ No broken wikilinks found" >> "$REPORT"
else
    echo "" >> "$REPORT"
    echo "**Total broken links:** $BROKEN_LINKS" >> "$REPORT"
    ISSUE_COUNT=$((ISSUE_COUNT + BROKEN_LINKS))
fi

echo "  Found: $BROKEN_LINKS broken links"
echo "" >> "$REPORT"

# ============ CHECK 2: MISSING/INCOMPLETE FRONTMATTER ============
echo "[2/5] Checking frontmatter completeness..."

echo "## 📝 Frontmatter Issues" >> "$REPORT"
echo "" >> "$REPORT"

FRONTMATTER_ISSUES=0
REQUIRED_FIELDS=("type" "category")

while IFS= read -r file; do
    rel_file="${file#$VAULT_ROOT/}"
    
    # Skip daily notes, root files, and README
    if echo "$rel_file" | grep -qE "Daily_Notes|^CLAUDE|^GEMINI|^Untitled|^agents"; then
        continue
    fi
    
    # Check if file has frontmatter
    first_line=$(head -1 "$file" 2>/dev/null)
    if [ "$first_line" != "---" ]; then
        echo "- \`$rel_file\` — missing frontmatter" >> "$REPORT"
        FRONTMATTER_ISSUES=$((FRONTMATTER_ISSUES + 1))
        continue
    fi
    
    # Check required fields
    for field in "${REQUIRED_FIELDS[@]}"; do
        if ! head -20 "$file" | grep -q "^${field}:"; then
            echo "- \`$rel_file\` — missing \`${field}:\` in frontmatter" >> "$REPORT"
            FRONTMATTER_ISSUES=$((FRONTMATTER_ISSUES + 1))
        fi
    done
done < <(find "$VAULT_ROOT" -name "*.md" -not -path "*/.git/*" -not -path "*/.obsidian/*" -not -path "*/claude_memory/*")

if [ $FRONTMATTER_ISSUES -eq 0 ]; then
    echo "✓ All frontmatter complete" >> "$REPORT"
else
    echo "" >> "$REPORT"
    echo "**Total issues:** $FRONTMATTER_ISSUES" >> "$REPORT"
    ISSUE_COUNT=$((ISSUE_COUNT + FRONTMATTER_ISSUES))
fi

echo "  Found: $FRONTMATTER_ISSUES frontmatter issues"
echo "" >> "$REPORT"

# ============ CHECK 3: ORPHAN FILES (no incoming wikilinks) ============
echo "[3/5] Checking for orphan files..."

echo "## 🏝️ Orphan Files" >> "$REPORT"
echo "" >> "$REPORT"
echo "> Files with no incoming wikilinks (potentially disconnected from vault)" >> "$REPORT"
echo "" >> "$REPORT"

ORPHANS=0

while IFS= read -r file; do
    rel_file="${file#$VAULT_ROOT/}"
    filename=$(basename "$file" .md)
    
    # Skip index files and CLAUDE files and daily notes
    if echo "$rel_file" | grep -qE "index|CLAUDE|GEMINI|Daily_Notes|Navigation_Map|agents|Untitled|rekam_jejak"; then
        continue
    fi
    
    # Check if any other file links to this
    incoming=$(grep -rl "\[\[$filename" "$VAULT_ROOT" --include="*.md" 2>/dev/null | grep -v "$file" | wc -l)
    
    if [ $incoming -eq 0 ]; then
        echo "- \`$rel_file\`" >> "$REPORT"
        ORPHANS=$((ORPHANS + 1))
    fi
done < <(find "$VAULT_ROOT" -name "*.md" -not -path "*/.git/*" -not -path "*/.obsidian/*" -not -path "*/claude_memory/*")

if [ $ORPHANS -eq 0 ]; then
    echo "✓ No orphan files found" >> "$REPORT"
else
    echo "" >> "$REPORT"
    echo "**Total orphans:** $ORPHANS (not critical — review manually)" >> "$REPORT"
fi

echo "  Found: $ORPHANS orphan files"
echo "" >> "$REPORT"

# ============ CHECK 4: REKAM JEJAK SIZE ============
echo "[4/5] Checking rekam_jejak size..."

echo "## 📊 Rekam Jejak Size" >> "$REPORT"
echo "" >> "$REPORT"

if [ -f "$REKAM_JEJAK" ]; then
    FILE_SIZE=$(wc -c < "$REKAM_JEJAK")
    LINE_COUNT=$(wc -l < "$REKAM_JEJAK")
    ENTRY_COUNT=$(grep -c "^### 202" "$REKAM_JEJAK" 2>/dev/null || echo 0)
    
    echo "- Size: ${FILE_SIZE} bytes" >> "$REPORT"
    echo "- Lines: ${LINE_COUNT}" >> "$REPORT"
    echo "- Entries: ${ENTRY_COUNT}" >> "$REPORT"
    echo "" >> "$REPORT"
    
    echo "  Size: ${FILE_SIZE} bytes, $ENTRY_COUNT entries"
    
    if [ $FILE_SIZE -gt 204800 ]; then  # >200KB
        echo "⚠️  CRITICAL: rekam_jejak.md >200KB — run daily-housekeeping.sh NOW" >> "$REPORT"
        echo "  ⚠️  CRITICAL: rekam_jejak.md >200KB — compact needed!"
        ISSUE_COUNT=$((ISSUE_COUNT + 1))
    elif [ $FILE_SIZE -gt 102400 ]; then  # >100KB
        echo "⚠️  WARNING: rekam_jejak.md >100KB — consider compacting soon" >> "$REPORT"
        echo "  ⚠️  WARNING: rekam_jejak.md >100KB — compact recommended"
    else
        echo "✓ rekam_jejak.md size OK" >> "$REPORT"
        echo "  ✓ Size OK"
    fi
fi

echo "" >> "$REPORT"

# ============ CHECK 5: KEYWORD MAP STALENESS ============
echo "[5/5] Checking keyword map coverage..."

echo "## 🗺️ Keyword Map Coverage" >> "$REPORT"
echo "" >> "$REPORT"

if [ -f "$KEYWORD_MAP" ]; then
    KEYWORD_COUNT=$(wc -l < "$KEYWORD_MAP")
    echo "- Total keywords: $((KEYWORD_COUNT - 1))" >> "$REPORT"  # minus header
    echo ""  >> "$REPORT"
    
    # Check if project files in 01_BACKEND_PROJECTS have entries in keyword map
    echo "### Unmapped Project Files:" >> "$REPORT"
    
    UNMAPPED=0
    while IFS= read -r file; do
        filename=$(basename "$file" .md)
        if ! grep -q "^$filename" "$KEYWORD_MAP" 2>/dev/null; then
            echo "- \`$filename\` (01_BACKEND_PROJECTS) — not in keyword map" >> "$REPORT"
            UNMAPPED=$((UNMAPPED + 1))
        fi
    done < <(find "$VAULT_ROOT/01_BACKEND_PROJECTS (Active development)" -name "*.md" -not -name "index.md")
    
    if [ $UNMAPPED -eq 0 ]; then
        echo "✓ All project files mapped" >> "$REPORT"
    else
        echo "" >> "$REPORT"
        echo "**Total unmapped:** $UNMAPPED" >> "$REPORT"
        ISSUE_COUNT=$((ISSUE_COUNT + UNMAPPED))
    fi
    
    echo "  Keyword coverage: $((KEYWORD_COUNT - 1)) keywords, $UNMAPPED unmapped project files"
fi

echo "" >> "$REPORT"

# ============ SUMMARY ============

echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## 📋 Summary" >> "$REPORT"
echo "" >> "$REPORT"
echo "| Check | Status |" >> "$REPORT"
echo "|---|---|" >> "$REPORT"
echo "| Broken wikilinks | $BROKEN_LINKS issues |" >> "$REPORT"
echo "| Frontmatter | $FRONTMATTER_ISSUES issues |" >> "$REPORT"
echo "| Orphan files | $ORPHANS files |" >> "$REPORT"
echo "| Rekam jejak size | ${FILE_SIZE:-0} bytes |" >> "$REPORT"
echo "| Unmapped keywords | $UNMAPPED files |" >> "$REPORT"
echo "" >> "$REPORT"
echo "**Total actionable issues: $ISSUE_COUNT**" >> "$REPORT"
echo "" >> "$REPORT"
echo "> Next: resolve issues above, then \`git sync\` vault." >> "$REPORT"

echo ""
echo "════════════════════════════════════════════"
echo "  ✅ Vault Health Check complete"
echo "  📊 Total actionable issues: $ISSUE_COUNT"
echo "  📄 Report: 00_INBOX/vault_health_$(date +%Y-%m-%d).md"
echo "════════════════════════════════════════════"
echo ""
